---
abstract: 'Manage a set of DBI handles'
author:
  - 'Dave Rolsky, <autarch@urth.org>'
build_requires:
  DBD::Mock: 1.38
  Fey::Test: 0.04
  Test::More: 0.88
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3603'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Fey-DBIManager
provides:
  Fey::DBIManager:
    file: lib/Fey/DBIManager.pm
    version: 0.11
  Fey::DBIManager::Source:
    file: lib/Fey/DBIManager/Source.pm
    version: 0.11
requires:
  Fey: 0.12
  Moose: 0.90
  MooseX::SemiAffordanceAccessor: 0.05
  MooseX::StrictConstructor: 0.08
  namespace::autoclean: 0
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Fey-DBIManager
  homepage: http://www.fey-project.org/
  license: http://dev.perl.org/licenses/
  repository: http://hg.urth.org/hg/Fey-DBIManager
version: 0.11
