---
name: Fey-DBIManager
version: 0.10
author:
  - 'Dave Rolsky, <autarch@urth.org>'
abstract: Manage a set of DBI handles
license: perl
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Fey-DBIManager
  homepage: http://www.fey-project.org/
  license: http://dev.perl.org/licenses/
  repository: http://hg.urth.org/hg/Fey-DBIManager
requires:
  Fey: 0.12
  Moose: 0.56
  MooseX::AttributeHelpers: 0.13
  MooseX::SemiAffordanceAccessor: 0.03
  MooseX::StrictConstructor: 0.07
build_requires:
  DBD::Mock: 1.38
  Fey::Test: 0.04
  Test::More: 0
provides:
  Fey::DBIManager:
    file: lib/Fey/DBIManager.pm
    version: 0.10
  Fey::DBIManager::Source:
    file: lib/Fey/DBIManager/Source.pm
generated_by: Module::Build version 0.31012
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
